ResponsiveImagesCG/wp-tevko-responsive-images

wp-tevko-responsive-images.php

Adding a filter to also add srcset attributes to featured images.

filter post thumbnail html

---

readme.txt

Update my attribution so it connects with my wp.org handle
:(

update attribution so it links properly in wp.org repository

---

wp-tevko-responsive-images.php

Update docblocks for all PHP functions

---

readme.md

Improved code (may be dequeued too early) & links to various docs

Update readme.md re: disabling Picturefill

---

class-respimg.php
class-wp-image-editor-respimg.php
wp-tevko-responsive-images.php

Smart resize

---

wp-tevko-responsive-images.php

Replaces PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/82

Improve performance of get_srcset_array

---

wp-tevko-responsive-images.php

Replaces PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/73

Use wp_get_attachment_image_attributes filter for post thumbnails

---

readme.md

Fix typo and clarify tevkori_get_srcset_array readme example (fixes #90)

---

wp-tevko-responsive-images.php

Replaces PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/85 / commit 51180d8

Typo fixes, comments, and coding standards

---

wp-tevko-responsive-images.php

Move list of included libraries below plugin header.

---

wp-tevko-responsive-images.php

It looks like some unintentional changes were made when resolving conflicts (commit ddeacce).

Revert unintentional changes in comments

---

readme.txt

Fixes an issue with the layout of the readme on WordPress.org

Readme layout fix

---

tests/test-suite.php

This is a test for #112 and should pass once #113 is merged.

Add test for when uploads dir not organized by date

---

composer.json

A reprise of #120, this time against `dev`.

Add Composer support.

---

wp-tevko-responsive-images.php

Replaces PR #110 / commit 0a29475

Check if wp_get_attachment_metadata returns an array

---

class-respimg.php
class-wp-image-editor-respimg.php
tests/bootstrap.php
wp-tevko-responsive-images.php

See commits for comments. I made also made unit tests work when part of an SVN or Git checkout.

Core cleanup

---

tests/test-suite.php
wp-tevko-responsive-images.php

Replaces PR #110 / commit eb2512b

Prevent duplicates in srcset array

---

.travis.yml

Add test for WordPress 4.1 and 4.2 to our test matrix.

Edit WP releases in Travis matrix

---

tests/test-suite.php

Fixed some docs formatting and removed unused variables in a few of our tests.

Test cleanup

---

readme.md

Change Newtons to Newton's in the Advanced Image Compression section of the docs, because grammar.

Add apostrophe in readme.md

---

tests/test-suite.php
wp-tevko-responsive-images.php

Why did I wait so long to do this?

Make output of tevkori_get_srcset_array filterable (Fixes #108)

---

tests/test-suite.php

This test should help us ensure that a content filter is working as expected.
cc: @jaspermdegroot @peterwilsoncc
See #170

Add tests for content filtering

---

.jshintrc
.linthub.yml
ruleset.xml

See https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/174

Add Linthub config

---

wp-tevko-responsive-images.php

I think we can remove this by now.

Remove deprecated tevkori_get_src_sizes

---

wp-tevko-responsive-images.php

I'm cherry-picking a couple of @peterwilsoncc's commits from #198 but leaving out the filter that addresses #190 for now.

Display filter improvements

---

tests/test-suite.php
wp-tevko-core-functions.php

See https://core.trac.wordpress.org/ticket/34528

Filter `srcset` attributes for animated GIFs.

---

tests/test-suite.php
wp-tevko-core-functions.php

I added a test for it which should fail when tested against WP trunk as long as we don't make the same change there.

Check if there is no sizes attribute before adding it

---

readme.md

Document the `max_srcset_image_width` hook.

---

readme.md
readme.txt

* Bumped release numbers
* Added changelog entries
* Added a section for WP.org about compatibility with WP 4.4.

3.1.0 Readme updates

---

wp-tevko-core-functions.php

See https://core.trac.wordpress.org/changeset/35715

Added see tags

---

readme.md
readme.txt
tests/test-suite.php
wp-tevko-core-functions.php
wp-tevko-deprecated-functions.php
wp-tevko-responsive-images.php

Prepping to merge dev changes into master for the release of 3.1.1.

Version 3.1.1
