ResponsiveImagesCG/wp-tevko-responsive-images

wp-tevko-responsive-images.php

I'd like to propose dropping the custom image sizes and relying on the default WordPress image sizes instead. For most images, this would result in three options for the browser to choose from: the medium size, the large size, and the full size. If a theme defined any other custom image sizes of equal proportion, those would be included as srcset options as well.
My reasoning is that WordPress is already creating three crops of each image on upload (i.e. thumbnail, medium, and large), and creating four additional crops uses a non-trivial amount of server resources, particularly when a theme has added a few additional custom image sizes.
I believe this is the tactic Nacin was suggesting on Slack as well:
https://wordpress.slack.com/archives/feature-respimg/p1419393836000051

Use native wordpress sizes instead of creating extra crop sizes.

---

wp-tevko-responsive-images.php

The first commit uses the sizes attributes returned from `wp_get_attachment_image_src()` to calculate ratios, which fixes a a 'divided by zero' warning that would return if the named size was not found in `wp_get_attachment_metadata()` (Fixes #23).
The second and third commits update the way the ratio is being rounded (fixes #24).

Size selection improvements

---

js/wp-tevko-responsive-images.js
wp-tevko-responsive-images.php

I noticed that the srcset attribute doesn't get recalculated when the image size is changed in the editor, which can lead to incorrect srcset values on an image. For example, if the image size is edited from one of the default sizes to the thumbnail, the srcset values would need to change (and vice versa).
This commit adds a script that listens for the `editor:image-update` event and recalculates the srcset if the image url has changed (i.e., a different size has been selected).

Recalculate srcset attribute if image is updated in the editor

---

wp-tevko-responsive-images.php

Instead of calculating ratios and then rounding, a better method is to calculate what the src image's height would be if it were resized to the same width as the target size and see if the two heights match.
Fixes #24

Improve the way srcset candidates are calculated

---

js/wp-tevko-responsive-images.js

When calculating expected sizes for `srcset` candidates in the updater, the rounding could be off by a single pixel. Now if the height of an image size is within 1 integer of the expected height in either direction, we let it pass.
(Fixes #37)

Fix rounding bug in update editor JS

---

wp-tevko-responsive-images.php

Adjusts the aspect ratio check in `tevkori_get_srcset_array()` to account for rounding variance. Same as the issue fixed in 4314d38.
Fixes #53 (props @side777)

Account for rounding variance when matching ascpect ratios.

---

wp-tevko-responsive-images.php

Without setting the default params for when functions are called without passing a `$size` parameter, the intent was to default to 'thumbnail' in order to mimic the default behavior of `wp_get_attachment_image_src()`, but currently 'null' is being passed to `wp_get_attachment_image_src()`, which ends up returning the full size instead of the default 'thumbnail' size. This pull request fixes that issue by explicitly setting a default value for `$size` to 'thumbnail' in all functions.

Make default params for optional '$sizes' match docs

---

js/wp-tevko-responsive-images.js
tests/test-suite.php
wp-tevko-responsive-images.php

Here's an initial candidate for how we can handle default support for the `sizes` attribute in this plugin.
As discussed in #34, we need a way to set a smart default value for the `sizes` attribute when we are including a source set list using w descriptors. Otherwise, we run the risk of fooling the browser into downloading larger resources than necessary by assuming the image layout width is equal to 100% of the viewport width (among other issues). For the purpose of this pull request, I'm using the following pattern as the default for `sizes`:
```
sizes="( max-width: {{image-width}} ) 100vw, {{image-width}}"
```
In other words, when the viewport is less than or equal to the width of the main image, assume the image takes up the full screen width. If the viewport is greater than the …

Add support for the sizes attribute.

---

tests/test-suite.php

Not only is this a better way to write these tests, but if fixes a bug where a previously failed test could leave behind images that would cause future tests to fail due to an unexpected file name, e.g. `test-large.png` vs `test-large1.png`.

Remove hard coded image paths from srcset tests

---

readme.txt

Via a suggestion at WordCamp St. Louis from @ipstenu, who is on the plugin review team for WordPress.org.

Add Plugin URI to readme.txt

---

readme.md

Gives a basic example of overriding `sizes` by passing a set of arrays.

Add example for overriding the default sizes attribute.

---

readme.md

At some point it looks like the docs for `tevkori_get_srcset_array()` got mixed up with `tevkori_get_sizes_string()`. This PR fixes that issue and adds a usage example for `tevkori_get_srcset_array()`.

Add srcset array docs

---

js/wp-tevko-responsive-images.js

This fixes and issue where post.php or post-new.php is used without loading wp.media, as is the case when adding Advanced Custom Fields field groups, resulting in get the following JS error:
```
Uncaught TypeError: Cannot read property 'events' of undefined
/wordpress/wp-content/plugins/ricg-responsive-images/js/wp-tevko-responsive-images.js?ver=2.0.0 line 8
```
See details in this thread on the WP.org support forums:
https://wordpress.org/support/topic/bug-v211-uncaught-typeerror?replies=9#post-6704725

Check if wp.media exists before running JS

---

.editorconfig
js/wp-tevko-responsive-images.js
wp-tevko-responsive-images.php

This cleans up the plugin JS by abstracting the logic for updating the `srcset` and `sizes` attributes into their own functions. In order to grab all the available sizes for `srcset` attributes (see #80), I've added an our own AJAX function which will use the plugin internals to retrieve `srcset` values and pass them back to the editor instead of duplicating all of that logic in the JS.

Refactor the Plugin JS

---

js/wp-tevko-responsive-images.js
wp-tevko-responsive-images.php

* Use the native wp function so that proper header is sent and approriate `die()` function is used.
* Some cleanup to the `wp-tevko-responsive-images.js`
* Corrected accepted args to `wp_get_attachment_image_attributes` filter

Use native wp_send_json to send the output

---

wp-tevko-responsive-images.php

fixed: first char gets stripped from file name if there's no slash

Keep full size image names from having first letter stripped (#112)

---

tests/test-suite.php
wp-tevko-responsive-images.php

This is a quick fix for #118. I assume the issue is being caused by something filtering the `image_downsize()` function and returning `0` for the width. In those cases we should just bail early rather since we won't be able to calculate aspect ratios for our source candidates for `srcset` anyway.

Don't calculate a srcset when the image data returns no width.

---

.travis.yml

Noticed that we never updated the test matrix after WP released version 4.2. This changes our Travis CI builds to test against the latest three WP versions: 4.2, 4.1, and 4.0, and drops the 3.9 tests.

Update TravisCI matrix

---

tests/test-suite.php
wp-tevko-responsive-images.php

Add filter hook `tevkori_image_sizes_args` and includes basic unit tests (addresses #101).
First stab at adding a filter to `tevkori_get_sizes()` so developers can more easily override the default `sizes` attribute. This implementation filters the `$args` variable inside `tevkori_get_sizes()` before the function creates the sizes list, but after the default arguments have been applied.
The filter hook passes three arguments:
* **$args**   *(array)* The `$args` array to be filtered and returned.
* **$id**       *(int)* The post ID of the image.
* **$size**    *(string)* The name of the image crop size being affected.
Functions that hook into this filter should return an array in the form of the `$args` array for `tevkori_get_sizes()`.
**Ex: Changing the default sizes array based on the …

Add a filter for sizes.

---

wp-tevko-responsive-images.php

The ratio comparison currently misses out on some sizes. This is because the original size comes from the thumbnail, real-world example:
Original size: 188x480
Size full: 1563x4000 (Expected height: 1567 - difference is 4)
The ratio differences with my images is around 0.001, so 0.01 should be enough.

Compare aspect ratio in relative values, not absolute values

---

wp-tevko-responsive-images.php

The functions that return the ```srcset``` and ```sizes``` attributes or values could return ```false```. In the functions that add those attributes to the images we do not always check if ```false``` has been returned. This PR fixes that.

Filters shouldn't add sizes/scrset attributes if false has been returned

---

tests/test-suite.php
wp-tevko-responsive-images.php

This is a possible approach to #155, which is a tricky problem since WP core doesn't explicitly describe an image size as a crop vs an original. Feedback would be appreciated.

Use crop hashes to filter out originals from crops

---

tests/test-suite.php

Adds two tests, one that makes sure `srcset` and `sizes` attributes both get set when there are multiple intermediate sizes available (using the medium size) and another that ensures `srcset` and `sizes` attributes do not get set on an image with only one source (using the thumbnail size).

Add tests for tevkori_filter_attachment_image_attributes() (resolves #159)

---

.travis.yml

WordPress is testing against PHP7 in preparation for its upcoming release so we should as well. Following WP's lead, we can allow these tests to fail and still pass the build.

Add PHP7 tests

---

tests/test-suite.php
wp-tevko-responsive-images.php

We should consider returning an array in `tevkori_get_srcset_array()` when there is only a single source candidate and move the logic requiring multiple source candidates to `tevkori_get_srcset()` so we wouldn't add `srcset` value when it only contains a single source.

Return single source candidates in `tevkori_get_srcset_array()`

---

wp-tevko-responsive-images.php

We don't have to go over all images again to replace the ```data-sizes``` attribute by a ```sizes``` attribute.

Optimize backcompat replacement of data-sizes attribute

---

readme.md
readme.txt
wp-tevko-responsive-images.php

This is a tracking ticket for all final cleanup before the release.

Release 2.5.0 prep

---

wp-tevko-responsive-images.php

(and slight improvement to the regex)
Fixes:
`Undefined offset 1 in /path/to/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php:350`

Minor fix to prevent a potential undefined variable notice.

---

tests/test-suite.php
wp-tevko-responsive-images.php

Due to performance concerns, we've talked about removing the third fallback in our content filter in order to avoid the expensive query on the front end. The tradeoff is that `<img>` elements without a `wp-image-{id}` class will no longer have `srcset` and `sizes` attributes added. 
I've also updates tests.

Don't query the DB directly during content filter.

---

wp-tevko-responsive-images.php

This warms the WordPress object cache for `wp_get_attachment_metadata` calls using a `WP_Query` call.
* Collects image IDs in an array
* Queries attachments using IDs of said attachments
* cache is warm, the following calls to `wp_get_attachment_metadata` will not trigger a DB call

Filter cache warming

---

tests/test-suite.php
wp-tevko-responsive-images.php

These changes address some of the issues brought up by @azaozz in #187.
* In 5b99b4b we can avoid a call to `image_downsize()` in when creating `sizes` attributes by passing the image height and width directly to `tevkori_get_sizes()` through the `$atts` parameter.
* In a96d0fc I cleaned up the regex in the display filter and added a `preg_quote()` wrapper around `$path_to_upload_dir`. Feels like we should be able to eliminate one of the `preg_match` runs in the display filter but this is at least an improvement for now.

Streamlining code

---

wp-tevko-responsive-images.php

Several of our internal function are using 'thumbnail' as the default value for `$size`.
Since the 'thumbnail' size is usually a hard crop and is less likely to result in a `srcset`
list, it makes sense to switch that default to use 'medium' instead.
Resolves #192

Change default `$size` value for all function to 'medium'

---

wp-tevko-responsive-images.php

* Update default value for `$sizes` to 'medium' in inline docs.
* Add inline docs for new 'width' parameter available in `tevkori_get_sizes` functions.

Update inline docs for 2.5.2

---

wp-tevko-responsive-images.php

Following c3057fb, we should also avoid calling `image_downsize()` in
`tevkori_get_sizes()`. This commit uses only the useful bits from the
internals of the `image_downsize()` function to get the width of an
image given and `id` and `size`.
I've also been considering whether the internals of `tevkori_get_sizes()` could be simplified to only output our smart default, rather than accepting an array of arguments for creating complex `sizes` patterns. Since the value is filterable, devs can already modify this value however they want.

tevkori_get_sizes() improvements

---

wp-tevko-responsive-images.php

Now that we're no longer using a `preg_replace_callback` function in
`tevkori_filter_content_images()`, it doesn't make as much sense to use
the callback function the way we originally set it up. However, rather
that merging the two function, this turns the callback into a useful
utility function that accepts an `img` element and returns the HTML
including `srcset` and `sizes` attributes if we can.
Additionally, since we only add `srcset` and `sizes` when we're able to
parse the attachment id from the markup, we also no longer need to limit
our matches in the content filter by files containing the path to our
uploads folder. This resolves #190.

Filtering function updates

---

tests/test-suite.php
wp-tevko-core-functions.php
wp-tevko-deprecated-functions.php

See https://core.trac.wordpress.org/ticket/34612

Split `wp_get_attachment_image_sizes()` for internal consistency.

---

wp-tevko-deprecated-functions.php

Fixes ResponsiveImagesCG/wp-tevko-responsive-images#228

Deprecate wp_get_attachment_image_sizes filter

---

tests/test-suite.php
wp-tevko-deprecated-functions.php

@jaspermdegroot I've been playing with a way of doing this without the use of a global variable and came up with a few ways of streamlining the process, I think.
First, I added a helper function, `_tevkori_sizes_has_args()` that caches the parsed `$args` param from `tevkori_get_sizes()` (when applicable). The same helper function can also be used to unset the cached `$args` value by passing in `false`.
In your shim function, I test to see if there is a cached `$args` param or a filter hooked to `tevkori_image_sizes_args` and bail early if not (which you were already doing). 
When there is not a cached `$args` param but there is a filter, I recreate the default parsed `$args` from the original `tevkori_get_sizes()` instead of transforming the $sizes attribute into an array. Functionally, I …

Streamlining of 226 backcompat PR

---

tests/test-suite.php
wp-tevko-deprecated-functions.php

When I was working on this I noticed I made a mistake in 2e13277c4896fdb17b2491044e057e185a364d85. The first commit fixes that.

Display a notice when deprecated filter hooks are used

---

tests/test-suite.php
wp-tevko-deprecated-functions.php

To avoid having a lot of duplicate code to make both the `tevkori_image_sizes_args` filter and the `$args` parameter of `tevkori_get_sizes()` work, I used a global variable. Any objections?

Fix backward compatibility of tevkori_image_sizes_args

---

tests/test-suite.php
wp-tevko-deprecated-functions.php

Fixes https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/245

Only show a warning when filters are actually used

---

tests/test-suite.php

I cherry-picked the commit from the 'fix-deprecation-warnings' branch (PR #246) to avoid merge conflicts. So we should merge that PR first and then rebase this 'cleanup-tests' branch to drop the commit before merging this PR.
I don't really understand how the `@group` numbering works. Some tests belong to a group, some don't. @joemcgill maybe you can give that look or explain it to me.

Cleanup tests

---

tests/test-suite.php
wp-tevko-core-functions.php
wp-tevko-deprecated-functions.php

This includes the upstream fixes from core that address #259, #260, and #261. It also adjusts a few of our internal test loading so that the filters applied to responsive images in Twenty Sixteen would not affect our expected results.

Apply Upstream Fixes
